CREATE TABLE games (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL UNIQUE,
	release_date INTEGER NOT NULL,
	genre_id INTEGER NOT NULL,
	platform_id INTEGER NOT NULL
);

CREATE TABLE players (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL
);

CREATE TABLE developers (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	office_room_id INTEGER NOT NULL
);

CREATE TABLE officerooms (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	room_name TEXT NOT NULL UNIQUE
);

CREATE TABLE sales (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	game_id INTEGER NOT NULL,
	player_id INTEGER NOT NULL,
	sale_date INTEGER NOT NULL,
	price INTEGER NOT NULL,

    FOREIGN KEY(game_id) REFERENCES games(id),
    FOREIGN KEY(player_id) REFERENCES players(id)
);

CREATE TABLE genres (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL
);

CREATE TABLE platforms (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL
);

CREATE TABLE ratings (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	game_id INTEGER NOT NULL,
	player_id INTEGER NOT NULL,
	rating INTEGER NOT NULL,
    FOREIGN KEY(game_id) REFERENCES games(id),
    FOREIGN KEY(player_id) REFERENCES players(id)
);

CREATE TABLE developed_by (
	developer_id INTEGER NOT NULL,
	game_id INTEGER NOT NULL,

    FOREIGN KEY(developer_id) REFERENCES developers(id),
    FOREIGN KEY(game_id) REFERENCES games(id)
);
